"""
Synthetic data generation for model-delta Phase 4 public deploy.

Generates 50,000 industrial/oilfield part records using real taxonomy labels
from asset-taxonomy-classifier, asking Haiku only to write Part Number +
Part Description. Labels are never generated by the model — zero risk of
hallucinated label names.

Usage:
    export ANTHROPIC_API_KEY=sk-ant-...
    cd ~/Code/model-delta
    python synthesis/generate.py

Output:
    synthesis/synthesized_50k.csv      — final CSV (gitignored)
    synthesis/checkpoint.jsonl         — crash-safe progress (gitignored)

Resume: re-run the same command — completed batches are skipped automatically.
"""

import csv
import json
import pathlib
import random
import sys
import time

import anthropic

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = pathlib.Path(__file__).parent.parent
TAXONOMY_PATH = (
    pathlib.Path.home()
    / "Code/asset-taxonomy-classifier/ml_pipeline/constraints/taxonomy_tree.json"
)
CHECKPOINT_PATH = REPO_ROOT / "synthesis" / "checkpoint.jsonl"
OUTPUT_PATH = REPO_ROOT / "synthesis" / "synthesized_50k.csv"

TARGET = 50_000
BATCH_SIZE = 50
BUSINESS_LINE = "SYNTHETIC"
RANDOM_SEED = 42

# ---------------------------------------------------------------------------
# Load taxonomy
# ---------------------------------------------------------------------------
with open(TAXONOMY_PATH) as f:
    taxonomy = json.load(f)

pf_list: list[str] = taxonomy["pf_allowed"]          # 75 PFs
pf_to_tech: dict[str, list[str]] = taxonomy["pf_to_tech"]
tech_to_brand: dict[str, list[str]] = taxonomy["tech_to_brand"]
brand_to_tool: dict[str, list[str]] = taxonomy["brand_to_tool"]


def sample_label_tuple(pf: str, rng: random.Random) -> tuple[str, str, str, str]:
    """Return (PF, TECH, BRAND, TOOLNAME) sampled top-down through hierarchy."""
    techs = pf_to_tech.get(pf, [])
    if not techs:
        return pf, "", "", ""
    tech = rng.choice(techs)
    brands = tech_to_brand.get(tech, [])
    if not brands:
        return pf, tech, "", ""
    brand = rng.choice(brands)
    tools = brand_to_tool.get(brand, [])
    toolname = rng.choice(tools) if tools else ""
    return pf, tech, brand, toolname


# ---------------------------------------------------------------------------
# Pre-generate all label tuples (no API calls, deterministic)
# ---------------------------------------------------------------------------
rng = random.Random(RANDOM_SEED)
records_per_pf = TARGET // len(pf_list)
remainder = TARGET - records_per_pf * len(pf_list)

all_tuples: list[tuple[str, str, str, str]] = []
for i, pf in enumerate(pf_list):
    count = records_per_pf + (1 if i < remainder else 0)
    for _ in range(count):
        all_tuples.append(sample_label_tuple(pf, rng))

assert len(all_tuples) == TARGET, f"Expected {TARGET} tuples, got {len(all_tuples)}"

# ---------------------------------------------------------------------------
# Resume: count rows already in checkpoint
# ---------------------------------------------------------------------------
completed_rows = 0
if CHECKPOINT_PATH.exists():
    with open(CHECKPOINT_PATH) as f:
        for line in f:
            line = line.strip()
            if line:
                completed_rows += 1

batches_done = completed_rows // BATCH_SIZE
skip_rows = batches_done * BATCH_SIZE
remaining_tuples = all_tuples[skip_rows:]

print(f"Taxonomy: {len(pf_list)} PFs, {len(taxonomy['tech_allowed'])} TECHs, "
      f"{len(taxonomy['brand_allowed'])} BRANDs, {len(taxonomy['tool_reference'])} TOOLs")
print(f"Target: {TARGET:,} records | Batch size: {BATCH_SIZE}")
print(f"Already done: {completed_rows:,} rows ({batches_done} batches) — resuming from row {skip_rows:,}")
print(f"Remaining: {len(remaining_tuples):,} rows")
print()

if not remaining_tuples:
    print("All batches complete. Building final CSV...")
else:
    # -----------------------------------------------------------------------
    # Generate
    # -----------------------------------------------------------------------
    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env

    def generate_batch(batch: list[tuple[str, str, str, str]]) -> list[dict]:
        """Call Haiku to generate Part Number + Part Description for each tuple."""
        lines = "\n".join(
            f'{i+1}. PF="{pf}" | TECH="{tech}" | BRAND="{brand}" | TOOL="{toolname}"'
            for i, (pf, tech, brand, toolname) in enumerate(batch)
        )
        prompt = f"""You are generating realistic industrial equipment part records for oilfield/completions equipment.

For each numbered item below, output ONLY a JSON array element with these two fields:
- "part_number": an 8-digit numeric string (e.g. "10039031") — make each unique
- "description": a 3-10 word UPPERCASE technical English part description realistic for the given equipment type

Output a single JSON array with exactly {len(batch)} objects, in the same order as the input. No other text.

Items:
{lines}"""

        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=4096,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = response.content[0].text.strip()
        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        batch_result = json.loads(raw)
        return batch_result

    CHECKPOINT_PATH.parent.mkdir(parents=True, exist_ok=True)
    total_batches = (len(remaining_tuples) + BATCH_SIZE - 1) // BATCH_SIZE
    errors = 0

    with open(CHECKPOINT_PATH, "a") as ckpt_file:
        for batch_idx in range(total_batches):
            start = batch_idx * BATCH_SIZE
            batch_tuples = remaining_tuples[start : start + BATCH_SIZE]
            global_row = skip_rows + start

            attempts = 0
            while attempts < 3:
                try:
                    results = generate_batch(batch_tuples)
                    if len(results) != len(batch_tuples):
                        raise ValueError(
                            f"Expected {len(batch_tuples)} results, got {len(results)}"
                        )
                    break
                except (json.JSONDecodeError, ValueError, KeyError) as e:
                    attempts += 1
                    print(f"  Batch {batch_idx+1} parse error (attempt {attempts}): {e}")
                    time.sleep(2)
            else:
                print(f"  Batch {batch_idx+1} failed after 3 attempts — skipping")
                errors += 1
                time.sleep(2)
                continue

            for i, (pn_desc, (pf, tech, brand, toolname)) in enumerate(
                zip(results, batch_tuples)
            ):
                row = {
                    "Part Number": pn_desc.get("part_number", ""),
                    "Part Description": pn_desc.get("description", ""),
                    "PRODUCT_FAMILY_NAME": pf,
                    "TECHNOLOGY_NAME": tech,
                    "BRAND_NAME": brand,
                    "TOOLNAME": toolname,
                    "BUSINESS_LINE_NAME": BUSINESS_LINE,
                }
                ckpt_file.write(json.dumps(row) + "\n")

            ckpt_file.flush()

            done = global_row + len(batch_tuples)
            pct = done / TARGET * 100
            print(
                f"Batch {batches_done + batch_idx + 1}/{batches_done + total_batches} "
                f"| rows {global_row}–{done-1} "
                f"| {done:,}/{TARGET:,} ({pct:.1f}%)"
            )
            time.sleep(0.5)

    print(f"\nGeneration complete. Errors: {errors}")

# ---------------------------------------------------------------------------
# Write final CSV from checkpoint
# ---------------------------------------------------------------------------
print(f"Writing {OUTPUT_PATH} ...")
FIELDNAMES = [
    "Part Number",
    "Part Description",
    "PRODUCT_FAMILY_NAME",
    "TECHNOLOGY_NAME",
    "BRAND_NAME",
    "TOOLNAME",
    "BUSINESS_LINE_NAME",
]

rows = []
with open(CHECKPOINT_PATH) as f:
    for line in f:
        line = line.strip()
        if line:
            rows.append(json.loads(line))

with open(OUTPUT_PATH, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
    writer.writeheader()
    writer.writerows(rows)

print(f"Done. {len(rows):,} rows written to {OUTPUT_PATH}")

# Quick sanity check
import collections
pf_counts = collections.Counter(r["PRODUCT_FAMILY_NAME"] for r in rows)
print(f"Unique PFs: {len(pf_counts)}")
print(f"Rows with empty TECH: {sum(1 for r in rows if not r['TECHNOLOGY_NAME'])}")
print(f"Rows with empty TOOLNAME: {sum(1 for r in rows if not r['TOOLNAME'])}")
